server:
  port: 8082
logging:
  level:
    root: WARN
spring:
  thymeleaf:
    cache: false

---

spring:
  profiles: securityDisabled
  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration